first commit

diff --git a/lib/kapow b/lib/kapow
--- a/lib/kapow
+++ b/lib/kapow
@@ -1,19 +1,20 @@
 KAPOW_LIB="/Users/dan/Code/kapow/lib/"
-KAPOW_REPO="http://github.com/danryan/kapow_repo/"
-function install_pkg {
-	echo "Installing $1..."
-	
+KAPOW_FORMULAE="http://github.com/danryan/kapow_repo/"
+
+
+do_install() {
+	echo "Installing $1..."	
 }
 
-function remove_pkg {
+do_remove() {
 	echo "Removing $1..."
 }
 
-function search_pkg {
+do_search() {
 	echo "Searching for $1..."
 }
 
-function require {
+require() {
   if [ -f $KAPOW_LIB$1 ] && [ -r $KAPOW_LIB$1 ] 
 	then
 		echo $1
@@ -21,4 +22,9 @@ function require {
 	else
 		echo "File could not be read or does not exist." && exit
   fi
+}
+
+die() {
+  echo -e "kapow error:  $1" 1>&2
+  exit 255
 }
